### ISSUE TITLE
Minor Misleading comment in ez_switch_lib_interrupt.ino

### ISSUE THREAD

**Issue by Blend3rman** [ronbentley1/ez_switch_lib-Arduino-Library#1]
The comment on Line 51 mentions:
` // [][1] = digital output pin connected to switch`

But in line 70, `ms.add_switch()` is called, which means that  the 2nd param is the *INPUT* pin connected to the switch:
```cpp 
   my_switches[sw][2] = ms.add_switch( 
                         my_switches[sw][0],  // switch type 
                         my_switches[sw][1],  // digital pin switch is wired to <<<
                         my_switches[sw][3]); // type of circuit switch is wired as
``` 

Just a minor correction, but it was a point of confusion for me. Maybe the comment could be updated as
`// [][1] = digital input pin the switch is wired to`

**Comment by ronbentley1** [comment]
First of all, hello, and thank you for your diligence in picking up this issue.

I can see the point of confusion and I have updated the .ino code to to remove the word "output", together with the same change in the User Guide copy of this code.

I am very rewarded to know that there are coders and users out there with the interest to examine my work in detail.  Many thanks.
